default_agent: returns_refunds_agent
agents:
  returns_refunds_agent:
    name: returns_refunds_agent
    language: python
    node_version: null
    entrypoint: /home/workshop/Project/17_runtime_agent.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: null
    aws:
      execution_role: arn:aws:iam::089884621935:role/ReturnsAgentRuntimeExecutionRole
      execution_role_auto_create: false
      account: 089884621935
      region: us-west-2
      ecr_repository: null
      ecr_auto_create: true
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: returns_refunds_agent-64gK817lBI
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:089884621935:runtime/returns_refunds_agent-64gK817lBI
      agent_session_id: b3ac6f2e-094a-4309-a57c-216a64f19bfb
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration:
      customJWTAuthorizer:
        allowedClients:
        - 1pc54nf10lvciqe741c7t4v4ug
        discoveryUrl: https://cognito-idp.us-west-2.amazonaws.com/us-west-2_8OrM4cNDS/.well-known/openid-configuration
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
